// Generated by json-schema-to-typescript from schemas/greeting.json. DO NOT EDIT.
// Deliberately left as a generator writes it: not Prettier-formatted, and
// with an `any` ESLint would reject. vibe.yaml declares src/contracts/** as
// generated, so neither tool checks it; tsc still does (spec 0037).

export interface Greeting { name : string; extra?: any }
