// Command guard is the PreToolUse guard Claude Code and Codex call through
// "task -x hook:guard". It reads one tool call as JSON on stdin, matches it
// against the rules in the policy file named by its only argument, and
// denies by exiting 2 with the reason on stderr. Anything else exits 0.
//
// Generated by VibeConform (prod-go/v1, repo-tooling). The Node and Python
// guards in prod-ts and prod-py implement the same contract; a shared test
// corpus keeps the three in agreement. See
// docs/specs/0021-agent-hooks-task-interface.md in the VibeConform
// repository.
//
// Standard library only, so "go run" needs nothing downloaded. It lives
// under .claude/, which go build ./..., go vet, and golangci-lint all skip,
// so it never becomes part of this repository's own module.
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"regexp"
	"slices"
)

// exitDeny is the exit code both agents read as "block this tool call".
const exitDeny = 2

type rule struct {
	ID      string `json:"id"`
	Field   string `json:"field"`
	Pattern string `json:"pattern"`
	Raw     string `json:"raw"`
	Message string `json:"message"`
}

type policy struct {
	Version int                 `json:"version"`
	Tools   map[string][]string `json:"tools"`
	Rules   []rule              `json:"rules"`
}

type toolCall struct {
	ToolName  string         `json:"tool_name"`
	ToolInput map[string]any `json:"tool_input"`
}

func main() {
	if len(os.Args) != 2 {
		deny("guard: usage: guard <policy.json>; blocking until the hook:guard task is fixed")
	}
	p, err := loadPolicy(os.Args[1])
	if err != nil {
		// Fail closed: a guard that cannot read its policy cannot tell a
		// destructive command from a safe one.
		deny(fmt.Sprintf("guard: %v; blocking until the policy file is fixed", err))
	}

	stdin, err := io.ReadAll(os.Stdin)
	if err != nil {
		deny(fmt.Sprintf("guard: reading stdin: %v", err))
	}

	if msg, ok := check(p, stdin); ok {
		deny(msg)
	}
}

func loadPolicy(path string) (*policy, error) {
	data, err := os.ReadFile(path) // #nosec G304 G703 -- the path is the hook:guard task's own fixed argument
	if err != nil {
		return nil, fmt.Errorf("reading policy: %w", err)
	}
	var p policy
	if err := json.Unmarshal(data, &p); err != nil {
		return nil, fmt.Errorf("parsing policy %s: %w", path, err)
	}
	if p.Version != 1 {
		return nil, fmt.Errorf("policy %s has version %d; this guard understands version 1", path, p.Version)
	}
	return &p, nil
}

// check returns the message of the first rule the tool call matches.
//
// The parsed field is matched when the payload parses, names a known tool,
// and carries that tool's field as a string. Otherwise every rule's raw
// pattern is matched against the payload text, which is exactly what the
// bash hooks did before this guard replaced them: never less strict.
func check(p *policy, stdin []byte) (string, bool) {
	var call toolCall
	if err := json.Unmarshal(stdin, &call); err == nil {
		if field, ok := fieldFor(p, call.ToolName); ok {
			if value, ok := call.ToolInput[field].(string); ok {
				for _, r := range p.Rules {
					if r.Field == field && matches(r.Pattern, value) {
						return r.Message, true
					}
				}
				return "", false
			}
		}
	}

	text := string(stdin)
	for _, r := range p.Rules {
		if matches(r.Raw, text) {
			return r.Message, true
		}
	}
	return "", false
}

func fieldFor(p *policy, toolName string) (string, bool) {
	for field, tools := range p.Tools {
		if slices.Contains(tools, toolName) {
			return field, true
		}
	}
	return "", false
}

// matches reports whether pattern matches s. A pattern that does not
// compile counts as a match: a broken rule must block rather than quietly
// stop guarding.
func matches(pattern, s string) bool {
	re, err := regexp.Compile(pattern)
	if err != nil {
		return true
	}
	return re.MatchString(s)
}

func deny(msg string) {
	_, _ = fmt.Fprintln(os.Stderr, msg)
	os.Exit(exitDeny)
}
