// PreToolUse guard that Claude Code and Codex call through
// "task -x hook:guard". It reads one tool call as JSON on stdin, matches it
// against the rules in the policy file named by its only argument, and
// denies by exiting 2 with the reason on stderr. Anything else exits 0.
//
// Generated by VibeConform (prod-ts/v1, ts-repo-tooling). The Go and Python
// guards in prod-go and prod-py implement the same contract; a shared test
// corpus keeps the three in agreement. See
// docs/specs/0021-agent-hooks-task-interface.md in the VibeConform
// repository.
//
// Node standard library only, so it runs without anything installed.
import { readFileSync } from 'node:fs'

// The exit code both agents read as "block this tool call".
const EXIT_DENY = 2

function deny(message) {
  process.stderr.write(`${message}\n`)
  process.exit(EXIT_DENY)
}

function loadPolicy(path) {
  let policy
  try {
    policy = JSON.parse(readFileSync(path, 'utf8'))
  } catch (err) {
    throw new Error(`reading policy ${path}: ${err.message}`, { cause: err })
  }
  if (policy.version !== 1) {
    throw new Error(
      `policy ${path} has version ${policy.version}; this guard understands version 1`,
    )
  }
  return policy
}

// A pattern that does not compile counts as a match: a broken rule must
// block rather than quietly stop guarding.
function matches(pattern, s) {
  try {
    return new RegExp(pattern).test(s)
  } catch {
    return true
  }
}

function fieldFor(policy, toolName) {
  for (const [field, tools] of Object.entries(policy.tools)) {
    if (tools.includes(toolName)) {
      return field
    }
  }
  return undefined
}

// Returns the message of the first rule the tool call matches, or
// undefined. The parsed field is matched when the payload parses, names a
// known tool, and carries that tool's field as a string. Otherwise every
// rule's raw pattern is matched against the payload text, which is what the
// bash hooks did before this guard replaced them: never less strict.
function check(policy, stdin) {
  let call
  try {
    call = JSON.parse(stdin)
  } catch {
    call = undefined
  }
  if (call !== null && typeof call === 'object') {
    const field = fieldFor(policy, call.tool_name)
    const value = call.tool_input?.[field]
    if (field !== undefined && typeof value === 'string') {
      const rule = policy.rules.find((r) => r.field === field && matches(r.pattern, value))
      return rule?.message
    }
  }
  return policy.rules.find((r) => matches(r.raw, stdin))?.message
}

function main() {
  if (process.argv.length !== 3) {
    deny('guard: usage: guard <policy.json>; blocking until the hook:guard task is fixed')
  }

  let policy
  try {
    policy = loadPolicy(process.argv[2])
  } catch (err) {
    // Fail closed: a guard that cannot read its policy cannot tell a
    // destructive command from a safe one.
    deny(`guard: ${err.message}; blocking until the policy file is fixed`)
  }

  let stdin = ''
  try {
    stdin = readFileSync(0, 'utf8')
  } catch (err) {
    // An empty or closed stdin is an ordinary empty payload, not an error.
    if (err.code !== 'EOF') {
      deny(`guard: reading stdin: ${err.message}`)
    }
  }

  const message = check(policy, stdin)
  if (message !== undefined) {
    deny(message)
  }
}

main()
