# generated by datamodel-codegen from schemas/greeting.json. DO NOT EDIT.
# Deliberately left as a generator writes it: not ruff-formatted, and with
# an unused import ruff would reject. vibe.yaml declares
# src/example/contracts/** as generated, so ruff skips it; pyright still
# checks it (spec 0037).
import os
from dataclasses import dataclass
@dataclass
class Greeting:
    name : str
