"""PreToolUse guard that Claude Code and Codex call through "task -x hook:guard".

It reads one tool call as JSON on stdin, matches it against the rules in the
policy file named by its only argument, and denies by exiting 2 with the
reason on stderr. Anything else exits 0.

Generated by VibeConform (prod-py/v1, py-repo-tooling). The Go and Node
guards in prod-go and prod-ts implement the same contract; a shared test
corpus keeps the three in agreement. See
docs/specs/0021-agent-hooks-task-interface.md in the VibeConform repository.

Standard library only, so "uv run --no-project" needs nothing installed.
"""

import json
import re
import sys

# The exit code both agents read as "block this tool call".
EXIT_DENY = 2


def deny(message: str) -> None:
    sys.stderr.write(message + "\n")
    sys.exit(EXIT_DENY)


def load_policy(path: str) -> dict:
    try:
        with open(path, encoding="utf-8") as f:
            policy = json.load(f)
    except (OSError, ValueError) as err:
        raise ValueError(f"reading policy {path}: {err}") from err
    if not isinstance(policy, dict) or policy.get("version") != 1:
        version = policy.get("version") if isinstance(policy, dict) else None
        raise ValueError(f"policy {path} has version {version}; this guard understands version 1")
    return policy


def matches(pattern: str, s: str) -> bool:
    """Report whether pattern matches s.

    A pattern that does not compile counts as a match: a broken rule must
    block rather than quietly stop guarding.
    """
    try:
        return re.search(pattern, s) is not None
    except re.error:
        return True


def field_for(policy: dict, tool_name: object) -> str | None:
    for field, tools in policy["tools"].items():
        if tool_name in tools:
            return field
    return None


def check(policy: dict, stdin: str) -> str | None:
    """Return the message of the first rule the tool call matches.

    The parsed field is matched when the payload parses, names a known tool,
    and carries that tool's field as a string. Otherwise every rule's raw
    pattern is matched against the payload text, which is what the bash hooks
    did before this guard replaced them: never less strict.
    """
    try:
        call = json.loads(stdin)
    except ValueError:
        call = None
    if isinstance(call, dict):
        field = field_for(policy, call.get("tool_name"))
        tool_input = call.get("tool_input")
        value = tool_input.get(field) if isinstance(tool_input, dict) else None
        if field is not None and isinstance(value, str):
            for rule in policy["rules"]:
                if rule["field"] == field and matches(rule["pattern"], value):
                    return rule["message"]
            return None
    for rule in policy["rules"]:
        if matches(rule["raw"], stdin):
            return rule["message"]
    return None


def main() -> None:
    if len(sys.argv) != 2:
        deny("guard: usage: guard <policy.json>; blocking until the hook:guard task is fixed")
    try:
        policy = load_policy(sys.argv[1])
    except ValueError as err:
        # Fail closed: a guard that cannot read its policy cannot tell a
        # destructive command from a safe one.
        deny(f"guard: {err}; blocking until the policy file is fixed")

    # Bytes, decoded explicitly: on Windows sys.stdin's text encoding is the
    # console code page, not UTF-8.
    stdin = sys.stdin.buffer.read().decode("utf-8", errors="replace")

    message = check(policy, stdin)
    if message is not None:
        deny(message)


if __name__ == "__main__":
    main()
